name: Autograding Tests
on:
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]' && github.actor != 'jacobsteffenBYU'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.6
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pandas openpyxl peewee pytest pytest-subtests 'black<=22.3.0' 'tomli>=1.1.0' 'timeout-decorator~=0.5.0'
    - name: tests/test_01_input_prompts.py
      id: tests-test-01-input-prompts-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-01-input-prompts
        setup-command: ''
        command: python -m pytest -v tests/test_01_input_prompts.py
        timeout: 30
        max-score: 5
    - name: tests/test_02_printed_messages.py
      id: tests-test-02-printed-messages-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-02-printed-messages
        setup-command: ''
        command: python -m pytest -v tests/test_02_printed_messages.py
        timeout: 30
        max-score: 15
    - name: tests/test_03_creating_single_movie.py
      id: tests-test-03-creating-single-movie-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-03-creating-single-movie
        setup-command: ''
        command: python -m pytest -v tests/test_03_creating_single_movie.py
        timeout: 30
        max-score: 10
    - name: tests/test_04_year_released_validation.py
      id: tests-test-04-year-released-validation-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-04-year-released-validation
        setup-command: ''
        command: python -m pytest -v tests/test_04_year_released_validation.py
        timeout: 30
        max-score: 12
    - name: tests/test_05_two_movies_no_updates.py
      id: tests-test-05-two-movies-no-updates-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-05-two-movies-no-updates
        setup-command: ''
        command: python -m pytest -v tests/test_05_two_movies_no_updates.py
        timeout: 30
        max-score: 10
    - name: tests/test_06_two_movies_updated_one.py
      id: tests-test-06-two-movies-updated-one-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-06-two-movies-updated-one
        setup-command: ''
        command: python -m pytest -v tests/test_06_two_movies_updated_one.py
        timeout: 30
        max-score: 10
    - name: tests/test_07_two_movies_updated_both.py
      id: tests-test-07-two-movies-updated-both-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-07-two-movies-updated-both
        setup-command: ''
        command: python -m pytest -v tests/test_07_two_movies_updated_both.py
        timeout: 30
        max-score: 10
    - name: tests/test_08_two_movies_deleted_one.py
      id: tests-test-08-two-movies-deleted-one-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-08-two-movies-deleted-one
        setup-command: ''
        command: python -m pytest -v tests/test_08_two_movies_deleted_one.py
        timeout: 30
        max-score: 10
    - name: tests/test_09_create_method_overridden.py
      id: tests-test-09-create-method-overridden-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-09-create-method-overridden
        setup-command: ''
        command: python -m pytest -v tests/test_09_create_method_overridden.py
        timeout: 30
        max-score: 13
    - name: tests/test_10_sufficient_comments.py
      id: tests-test-10-sufficient-comments-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test-10-sufficient-comments
        setup-command: ''
        command: python -m pytest -v tests/test_10_sufficient_comments.py
        timeout: 30
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-TEST-01-INPUT-PROMPTS-PY_RESULTS: ${{steps.tests-test-01-input-prompts-py.outputs.result}}
        TESTS-TEST-02-PRINTED-MESSAGES-PY_RESULTS: ${{steps.tests-test-02-printed-messages-py.outputs.result}}
        TESTS-TEST-03-CREATING-SINGLE-MOVIE-PY_RESULTS: ${{steps.tests-test-03-creating-single-movie-py.outputs.result}}
        TESTS-TEST-04-YEAR-RELEASED-VALIDATION-PY_RESULTS: ${{steps.tests-test-04-year-released-validation-py.outputs.result}}
        TESTS-TEST-05-TWO-MOVIES-NO-UPDATES-PY_RESULTS: ${{steps.tests-test-05-two-movies-no-updates-py.outputs.result}}
        TESTS-TEST-06-TWO-MOVIES-UPDATED-ONE-PY_RESULTS: ${{steps.tests-test-06-two-movies-updated-one-py.outputs.result}}
        TESTS-TEST-07-TWO-MOVIES-UPDATED-BOTH-PY_RESULTS: ${{steps.tests-test-07-two-movies-updated-both-py.outputs.result}}
        TESTS-TEST-08-TWO-MOVIES-DELETED-ONE-PY_RESULTS: ${{steps.tests-test-08-two-movies-deleted-one-py.outputs.result}}
        TESTS-TEST-09-CREATE-METHOD-OVERRIDDEN-PY_RESULTS: ${{steps.tests-test-09-create-method-overridden-py.outputs.result}}
        TESTS-TEST-10-SUFFICIENT-COMMENTS-PY_RESULTS: ${{steps.tests-test-10-sufficient-comments-py.outputs.result}}
      with:
        runners: tests-test-01-input-prompts-py,tests-test-02-printed-messages-py,tests-test-03-creating-single-movie-py,tests-test-04-year-released-validation-py,tests-test-05-two-movies-no-updates-py,tests-test-06-two-movies-updated-one-py,tests-test-07-two-movies-updated-both-py,tests-test-08-two-movies-deleted-one-py,tests-test-09-create-method-overridden-py,tests-test-10-sufficient-comments-py
